version: "3"

services:
  web:
    container_name: web
    image: klakegg/hugo:0.101.0
    ports:
      - "1313:1313"
    volumes:
      - ./:/src
    command: server --baseUrl http://grigolo.mt/ --appendPort=false
